const $=id=>document.getElementById(id);
async function api(path,method='GET',body){const r=await fetch(path,{method,credentials:'same-origin',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw new Error(data.error||'Campaign request failed');return data;}
export function setupCampaigns(){
  let campaigns=[],selected=null;const status=$('campaign-status'),form=$('campaign-form');
  const local=x=>x?new Date(new Date(x).getTime()-new Date(x).getTimezoneOffset()*60000).toISOString().slice(0,16):'';
  const payload=()=>({title:form.elements.title.value,body:form.elements.body.value,publishAt:form.elements.publishAt.value?new Date(form.elements.publishAt.value).toISOString():null,expiresAt:form.elements.expiresAt.value?new Date(form.elements.expiresAt.value).toISOString():null,tenantId:form.elements.audience.value==='all'?null:undefined});
  async function inbox(){const data=await api('/api/campaigns/inbox'),list=$('campaign-inbox');list.replaceChildren();for(const item of data.notifications){const li=document.createElement('li');li.textContent=`${item.title} · ${item.body} · ${new Date(item.publish_at).toLocaleString()} `;if(!item.acknowledged){const button=document.createElement('button');button.type='button';button.textContent='Acknowledge';button.onclick=async()=>{try{await api(`/api/campaigns/${item.id}/ack`,'POST',{});await inbox();}catch(e){$('campaign-inbox-status').textContent=e.message;}};li.append(button);}else li.append(' · Acknowledged');list.append(li);} $('campaign-inbox-status').textContent=`${data.notifications.filter(x=>!x.acknowledged).length} unread notification(s).`;}
  async function refresh(){const data=await api('/api/admin/campaigns');campaigns=data.campaigns;const list=$('campaign-list');list.replaceChildren();for(const c of campaigns){const li=document.createElement('li');const check=document.createElement('input');check.type='checkbox';check.value=c.id;check.setAttribute('aria-label',`Select ${c.title}`);li.append(check,document.createTextNode(` ${c.title} · ${c.status} · ${c.tenant_id?'Tenant':'All tenants'} · revision ${c.revision} `));const edit=document.createElement('button');edit.type='button';edit.textContent='Edit';edit.onclick=()=>{selected=c;form.elements.title.value=c.title;form.elements.body.value=c.body;form.elements.publishAt.value=local(c.publish_at);form.elements.expiresAt.value=local(c.expires_at);form.elements.audience.value=c.tenant_id?'tenant':'all';form.elements.audience.disabled=true;status.textContent=`Editing ${c.title}. Draft campaigns can be changed.`;};li.append(edit);list.append(li);}}
  form.onsubmit=async e=>{e.preventDefault();try{const body=payload();if(selected)await api(`/api/admin/campaigns/${selected.id}`,'PUT',{...body,revision:selected.revision});else await api('/api/admin/campaigns','POST',body);selected=null;form.reset();form.elements.audience.disabled=false;await refresh();status.textContent='Campaign draft saved.';}catch(error){status.textContent=error.message;}};
  $('campaign-new').onclick=()=>{selected=null;form.reset();form.elements.audience.disabled=false;status.textContent='New campaign draft.';};
  $('campaign-refresh').onclick=()=>refresh().catch(e=>status.textContent=e.message);
  $('campaign-inbox-refresh').onclick=()=>inbox().catch(e=>$('campaign-inbox-status').textContent=e.message);
  for(const action of ['publish','pause','archive'])$('campaign-'+action).onclick=async()=>{const ids=[...$('campaign-list').querySelectorAll('input:checked')].map(el=>el.value);if(!ids.length){status.textContent='Select campaigns first.';return;}let ok=0,fail=[];for(const id of ids){const c=campaigns.find(x=>x.id===id);try{await api(`/api/admin/campaigns/${id}/${action}`,'POST',{revision:c.revision});ok++;}catch(e){fail.push(`${c.title}: ${e.message}`);}}await refresh();await inbox();status.textContent=`${ok} campaign(s) processed (${action}).${fail.length?' '+fail.join('; '):''}`;};
  return {refresh:()=>refresh().catch(e=>status.textContent=e.message),inbox:()=>inbox().catch(e=>$('campaign-inbox-status').textContent=e.message)};
}
